name: Install Dependencies

on:
  push:
    branches:
      - '**'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Enable Corepack
        run: corepack enable
      - name: Install Dependencies
        run: pnpm install
